### ISSUE TITLE
Tengo hambre

### ISSUE THREAD

**Issue by Yondeivi** [Yondeivi/test1#1]
# Esto es un titulo
### Subtitulo 2 
Tengo hambre porque no he comido y no he conseguido un carajo
llevo dias buscando
hable con los 

> bachaqueros

fui a que los negocios 

- chen
- chin 
- chan

**Comment by joerod1** [comment]
si, ya va, deja la ladilla, ahi veo como resuelvo, gafo

**Comment by Yondeivi** [comment]
men esa verga estaba vencida, mardito loco

**Comment by joerod1** [comment]
ok chamo, ahorita les parto las piernas a esos marditos y veo que otra cosa consigo

**Comment by Yondeivi** [comment]
coño men te luciste ahora si xDD

**Comment by Yondeivi** [comment]
mira ,men revivieron esos marditos
