### ISSUE TITLE
Evento firestorm

### ISSUE THREAD

**Issue by Yondeivi** [Yondeivi/test1#2]
# Evento 
#  Tipo: No pvp 

Descipcion:

## antes del evento 
- Aparece un mensaje de que el evento inicio
- El player que quiera entrar usa !joinfs 
- El player es tpado a una sala de espera (pos asdasdasd)
- pasados x minutos empieza el evento si hay suficientes players, si no hay, los los de la lista de espera se van para esta pos xasdasd

## una vez iniciado el evento

- "meteoritos" caen del cielo y los players deben esquivarlos, si le llega a caer alguno, se jodio y perdio
- el queda es el que gana 
- el que gana, se gana alguno de estos items 43423, 324,234 ,34,3 

Mira, esto es algo parecido a lo que hiciste aqui #1

**Comment by joerod1** [comment]
chamo deja de joder :(
